import { jsPDF } from "jspdf";
import html2canvas from "html2canvas";

function formatNaira(amount) {
  return new Intl.NumberFormat("en-NG", { style: "currency", currency: "NGN", minimumFractionDigits: 2 })
    .format(amount ?? 0)
    .replace("NGN", "₦");
}

function formatDate(d) {
  if (!d) return "—";
  return new Date(d).toLocaleDateString("en-NG", {
    month: "long",
    day: "numeric",
    year: "numeric",
  });
}

function formatDateTime(d) {
  if (!d) return "—";
  return new Date(d).toLocaleString("en-NG", {
    month: "short",
    day: "numeric",
    year: "numeric",
    hour: "numeric",
    minute: "2-digit",
  });
}

function statusLabel(status) {
  const s = (status ?? "").toLowerCase();
  if (s === "success" || s === "successful") return "Successful";
  if (s === "failed") return "Failed";
  return "Pending";
}

function statusColors(label) {
  if (label === "Successful") return { bg: "#ECFDF5", fg: "#059669" };
  if (label === "Failed") return { bg: "#FEF2F2", fg: "#DC2626" };
  return { bg: "#FFFBEB", fg: "#B45309" };
}

function receiptRows(tx, payerName) {
  return [
    ["Description", tx.description ?? tx.planName ?? "Payment"],
    ["Community", tx.communityName ?? "—"],
    ["Paid by", payerName ?? "—"],
    ["Date", formatDate(tx.date)],
    ["Payment method", tx.channel ?? "—"],
    ["Reference", tx.reference ?? tx.id ?? "—"],
  ];
}

function receiptFilename(tx, ext) {
  return `glass-receipt-${tx.reference ?? tx.id ?? Date.now()}.${ext}`;
}

// ─────────────────────────────────────────────────────────────────────────────
// PDF receipt — a plain one-page document, good for records/printing.
// ─────────────────────────────────────────────────────────────────────────────
export function downloadReceiptPdf(tx, { payerName } = {}) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 56;
  let y = 64;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.setTextColor("#002FA7");
  doc.text("Glass", margin, y);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.setTextColor("#6b7280");
  doc.text("Payment Receipt", pageWidth - margin, y, { align: "right" });

  y += 12;
  doc.setDrawColor("#E5E7EB");
  doc.line(margin, y, pageWidth - margin, y);
  y += 40;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(28);
  doc.setTextColor("#111827");
  doc.text(formatNaira(tx.amount), margin, y);

  const status = statusLabel(tx.status);
  const colors = statusColors(status);
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(colors.fg);
  doc.text(status.toUpperCase(), pageWidth - margin, y, { align: "right" });

  y += 40;
  doc.setDrawColor("#E5E7EB");
  doc.line(margin, y, pageWidth - margin, y);
  y += 36;

  doc.setFontSize(11);
  for (const [label, value] of receiptRows(tx, payerName)) {
    doc.setFont("helvetica", "normal");
    doc.setTextColor("#6b7280");
    doc.text(label, margin, y);
    doc.setFont("helvetica", "bold");
    doc.setTextColor("#111827");
    doc.text(String(value), pageWidth - margin, y, { align: "right" });
    y += 26;
  }

  y += 20;
  doc.setDrawColor("#E5E7EB");
  doc.line(margin, y, pageWidth - margin, y);
  y += 30;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor("#9ca3af");
  doc.text(
    "This receipt was generated by Glass and reflects the payment record at the time of download.",
    margin,
    y,
    { maxWidth: pageWidth - margin * 2 },
  );

  doc.save(receiptFilename(tx, "pdf"));
}

// ─────────────────────────────────────────────────────────────────────────────
// Image receipt — a shareable card (Opay/Paystack-style), good for WhatsApp
// and social sharing. Built as an off-screen DOM node and rasterized with
// html2canvas rather than drawn on a <canvas> by hand, so the styling can
// just be plain CSS.
// ─────────────────────────────────────────────────────────────────────────────
export async function downloadReceiptImage(tx, { payerName } = {}) {
  const status = statusLabel(tx.status);
  const isSuccess = status === "Successful";

  const card = document.createElement("div");
  card.style.cssText = `
    position: fixed;
    left: -9999px;
    top: 0;
    width: 380px;
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Inter, sans-serif;
    background: #ffffff;
    border-radius: 20px;
    overflow: hidden;
    box-shadow: 0 1px 4px rgba(0,0,0,0.08);
  `;

  card.innerHTML = `
    <div style="background:#002FA7; padding:20px 24px 28px; text-align:center;">
      <div style="color:#ffffff; font-size:15px; font-weight:700; letter-spacing:0.2px;">Glass</div>
      <div style="width:56px; height:56px; border-radius:50%; background:rgba(255,255,255,0.15); display:flex; align-items:center; justify-content:center; margin:18px auto 14px;">
        <div style="width:40px; height:40px; border-radius:50%; background:${isSuccess ? "#16C147" : status === "Failed" ? "#E53E3E" : "#F59E0B"}; display:flex; align-items:center; justify-content:center;">
          <span style="color:#fff; font-size:20px; font-weight:700; line-height:1;">${isSuccess ? "✓" : status === "Failed" ? "✕" : "…"}</span>
        </div>
      </div>
      <div style="color:#ffffff; font-size:26px; font-weight:800;">${formatNaira(tx.amount)}</div>
      <div style="color:${isSuccess ? "#BFFFD1" : "#FFD9D9"}; font-size:12px; font-weight:700; margin-top:4px; letter-spacing:0.4px;">
        PAYMENT ${status.toUpperCase()}
      </div>
    </div>

    <div style="position:relative; height:0;">
      <div style="position:absolute; left:0; right:0; top:-11px; height:22px; background:
        radial-gradient(circle at 0 11px, transparent 11px, #fff 11.5px) 0 0 / 22px 22px repeat-x;
      "></div>
    </div>

    <div style="padding:28px 24px 8px;">
      ${receiptRows(tx, payerName)
        .map(
          ([label, value]) => `
        <div style="display:flex; justify-content:space-between; gap:12px; padding:9px 0; border-bottom:1px solid #F3F4F6;">
          <span style="font-size:12px; color:#9CA3AF;">${label}</span>
          <span style="font-size:12px; color:#111827; font-weight:600; text-align:right; max-width:220px; word-break:break-word;">${value}</span>
        </div>`,
        )
        .join("")}
    </div>

    <div style="padding:16px 24px 24px; text-align:center;">
      <div style="font-size:10px; color:#9CA3AF;">Generated by Glass · ${formatDateTime(new Date())}</div>
    </div>
  `;

  document.body.appendChild(card);
  try {
    const canvas = await html2canvas(card, { scale: 2, backgroundColor: "#ffffff" });
    const dataUrl = canvas.toDataURL("image/png");
    const link = document.createElement("a");
    link.href = dataUrl;
    link.download = receiptFilename(tx, "png");
    link.click();
  } finally {
    document.body.removeChild(card);
  }
}
